### ISSUE TITLE
actions/create-releaseをメンテナンスされてるやつに置き換える

### ISSUE THREAD

**Issue by book000** [book000/book000#11]
https://github.com/book000/templates/blob/master/.github/workflows/reusable-docker.yml

https://github.com/marketplace/actions/create-release

---

- [x] [book000/DiscordTerminal](https://github.com/book000/DiscordTerminal): [maven.yml](https://github.com/book000/DiscordTerminal/blob/0838fe423c62c17604303a940fe7c0c152785e00/.github/workflows/maven.yml)
- [x] [book000/EventFinder](https://github.com/book000/EventFinder): [release.yml](https://github.com/book000/EventFinder/blob/991d42c6a3369978ef75c4edbec6f21890777504/.github/workflows/release.yml)
- ~~[book000/GitHub-Actions-Test](https://github.com/book000/GitHub-Actions-Test): [maven.yml](https://github.com/book000/GitHub-Actions-Test/blob/ccfbe4de619b03f18b34e5bc0aa23e1b89bd0a22/.github/workflows/maven.yml)~~
- [x] [book000/MackerelSpigotWatcher](https://github.com/book000/MackerelSpigotWatcher): [release.yml](https://github.com/book000/MackerelSpigotWatcher/blob/a421a92a9214fdab39f4c2a8e6d48d08d18f871d/.github/workflows/release.yml)
- [x] [book000/SystemdLogTracker](https://github.com/book000/SystemdLogTracker): [maven.yml](https://github.com/book000/SystemdLogTracker/blob/b786b79010b72abf804627f03267efc55ba51dbf/.github/workflows/maven.yml)
- [x] [book000/node-utils](https://github.com/book000/node-utils): [release.yml](https://github.com/book000/node-utils/blob/bd39add756957f0c254fedddf0933b47e350b9ec/.github/workflows/release.yml)
- [x] [book000/pixivts](https://github.com/book000/pixivts): [release.yml](https://github.com/book000/pixivts/blob/71366fb2260b859637035327f7fb29854e3c8eee/.github/workflows/release.yml)
- [x] [jaoafa/AntiAlts3](https://github.com/jaoafa/AntiAlts3): [release.yml](https://github.com/jaoafa/AntiAlts3/blob/4599dffea274a3d8197247188a710c2b2aa52540/.github/workflows/release.yml)
- [x] [jaoafa/AwayFromKeyboard](https://github.com/jaoafa/AwayFromKeyboard): [release.yml](https://github.com/jaoafa/AwayFromKeyboard/blob/20a6af46c34ad8c887287d53acba88dbabce70c1/.github/workflows/release.yml)
- ~~[jaoafa/CheckRegionIntersects](https://github.com/jaoafa/CheckRegionIntersects): [maven.yml](https://github.com/jaoafa/CheckRegionIntersects/blob/121131e0e85840cc656598ffd38cfda78cda8637/.github/workflows/maven.yml)~~
- [x] [jaoafa/ChuoCity](https://github.com/jaoafa/ChuoCity): [release.yml](https://github.com/jaoafa/ChuoCity/blob/6c312799fe19fb87dca93111d4aa93462a234bd6/.github/workflows/release.yml)
- [x] [jaoafa/CrimicCosmos](https://github.com/jaoafa/CrimicCosmos): [release.yml](https://github.com/jaoafa/CrimicCosmos/blob/01552a12163eb12c5432119f9c1b90c2d6a42eb8/.github/workflows/release.yml)
- [x] [jaoafa/Gravel](https://github.com/jaoafa/Gravel): [release.yml](https://github.com/jaoafa/Gravel/blob/fca4921ca1bf16a6e3b4ce99d9701594b124bf77/.github/workflows/release.yml)
- [x] [jaoafa/Javajaotan2](https://github.com/jaoafa/Javajaotan2): [release.yml](https://github.com/jaoafa/Javajaotan2/blob/aecd5acb349057903e6bb5bc64053940a7586a85/.github/workflows/release.yml)
- [x] [jaoafa/MyMaid4](https://github.com/jaoafa/MyMaid4): [release.yml](https://github.com/jaoafa/MyMaid4/blob/4df0272f49a96325413a26dbfb1f7da06fbb0a1d/.github/workflows/release.yml)
- [x] [jaoafa/PeriodMatch2](https://github.com/jaoafa/PeriodMatch2): [release.yml](https://github.com/jaoafa/PeriodMatch2/blob/3699eca9f0f0eeeac63befddac55941ceaf85180/.github/workflows/release.yml)
- [x] [jaoafa/PluginWatcher](https://github.com/jaoafa/PluginWatcher): [release.yml](https://github.com/jaoafa/PluginWatcher/blob/7f6b1849c64f4503bdbc561d5c8b8328255892cc/.github/workflows/release.yml)
- [x] [jaoafa/adminwiki](https://github.com/jaoafa/adminwiki): [release.yml](https://github.com/jaoafa/adminwiki/blob/dbd1dcd2058d33fb3d32e2aae94d193c86dd5fac/.github/workflows/release.yml)
- [x] [jaoafa/coreprotect-splitter](https://github.com/jaoafa/coreprotect-splitter): [release.yml](https://github.com/jaoafa/coreprotect-splitter/blob/97058c780f4408f3eca63f19042dc3eb29a5bb94/.github/workflows/release.yml)
- [ ] [jaoafa/jao-Super-Achievement2](https://github.com/jaoafa/jao-Super-Achievement2): [release.yml](https://github.com/jaoafa/jao-Super-Achievement2/blob/283d39a8f3c15e5617969675c2258538f482ce20/.github/workflows/release.yml)
- ~~[jaoafa/jaoweb-docs](https://github.com/jaoafa/jaoweb-docs): [release.yml](https://github.com/jaoafa/jaoweb-docs/blob/30dbdb00379337f313077fed2e280b1222eafeea/.github/workflows/release.yml)~~: アーカイブ予定のため
- [x] [jaoafa/jaoweb-storage-node](https://github.com/jaoafa/jaoweb-storage-node): [release.yml](https://github.com/jaoafa/jaoweb-storage-node/blob/9b02a8f231453ed81003f722b7e406a526990771/.github/workflows/release.yml)

https://github.com/search?q=org%3Abook000+OR+org%3Atomacheese+OR+org%3Ajaoafa+create-release&type=code

---

```
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.calc-version.outputs.tag }}
          release_name: ${{ needs.calc-version.outputs.tag }}
          body: ${{ needs.calc-version.outputs.changelog }}
          draft: false
          prerelease: false
```

```
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ needs.calc-version.outputs.tag }}
          name: ${{ needs.calc-version.outputs.tag }}
          body: ${{ needs.calc-version.outputs.changelog }}
          draft: false
          prerelease: false
```

check:

```
custom_release_rules: "feat:minor:✨ Features,fix:patch:🐛 Fixes,docs:patch:📰 Docs,chore:patch:🎨 Chore,pref:patch:🎈 Performance improvements,refactor:patch:🧹 Refactoring,build:patch:🔍 Build,ci:patch:🔍 CI,revert:patch:⏪ Revert,style:patch:🧹 Style,test:patch:👀 Test,release:major:📦 Release"
```

```
ci: actions/create-release to ncipollo/release-action

ref: https://github.com/book000/book000/issues/11
```
